const CONFIG = {
    titleWeb: "To the one & only",
    introTitle: 'Hello Hoàng',
    introDesc: 'Happy White Valentines Day',
    btnIntro: 'Click here',
    title: 'Hoàng có gì muốn nói với em không?',
    desc: 'I Một điều gì đó...',
    btnYes: 'Of course',
    btnNo: 'I dont know',
    question: 'I miss u muchhh',
    btnReply: 'Send her',
    reply: 'Well,I miss u,too',
    mess: 'Em biết mà =)). Thương thương 🌷',
    messDesc: 'Hoàng mau hết bệnh nha',
    btnAccept: '❤️',
    messLink: 'https://m.me/tiiviviane.155'
