const CONFIG = {
    titleWeb: "To the one and only",
    introTitle: 'Hello Hoàng',
    introDesc: `Have a nice day`,
    btnIntro: 'Click here',
    title: 'Hoàng có gì muốn nói với em không?',
    desc: 'Một điều gì đó',
    btnYes: 'Tất nhiên rồi',
    btnNo: 'Anh không biết nữa',
    question: 'I miss u muchhh',
    btnReply: 'Send her',
    reply: 'Well,I miss u,too',
    mess: 'Em biết mà ☺️. Thương thương',
    messDesc: 'Hoàng mau khỏi bệnh rồi em dẫn Hoàng đi ăn lẩu nha',
    btnAccept: '❤️',
    messLink: 'https://m.me/tiiviviane.155'
